apiVersion: v1
kind: Service
metadata:
  name: app-golang-practice-service
  labels: 
    app: golang-rest-test
spec:
  type: NodePort
  selector:
    app: golang-rest-test
  ports:
    - port: 8888
      nodePort: 30390
      targetPort: 8888