apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-golang-practice-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: app-golang-practice-service
          servicePort: 8888